### ISSUE TITLE
How to deal with dynamic code.

### ISSUE THREAD

**Issue by late-init** [retrage/svc-hook#3]
Awesome project. I have a question: If the SVC instruction comes from dynamically generated code, how should we deal with it?

**Comment by retrage** [comment]
Good question.  Since typical dynamic code generation calls `mprotect` syscall before executing the code, we can hook the syscall at runtime, and do binary-rewriting to the target code. You can find the example for zpoline https://github.com/yasukata/zpoline/blob/master/Documentation/TIPS.md, which I previously proposed. The same method can be applied to svc-hook, too.

**Comment by late-init** [comment]
Thanks for your reply.
